name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: [ main ]

jobs:
  test-agent:
    name: Test nginx agent
    runs-on: ubuntu-20.04
    steps:
      - name: checkout otel nginx
        uses: actions/checkout@v2
      - name: setup
        run: |
          sudo ./ci/setup_test_environment.sh
      - name: build docker images
        run: |
          docker build -t otel-nginx-test/nginx -f test/Dockerfile .
          docker build -t otel-nginx-test/express-backend -f test/backend/simple_express/Dockerfile test/backend/simple_express
      - name: run tests
        run: |
          cd test/instrumentation
          mix local.hex --force --if-missing
          mix local.rebar --force --if-missing
          mix deps.get
          mix test
  build-agent:
    name: Build module
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: checkout otel nginx
        uses: actions/checkout@v2
      - name: setup
        run: |
          sudo ./ci/setup_ci_environment.sh
      - name: checkout grpc
        uses: actions/checkout@v2
        with: 
          repository: "grpc/grpc"
          ref: "v1.35.0"
          fetch-depth: 1
          path: "grpc"
          submodules: "recursive"
      - name: build grpc
        run: |
          ./ci/grpc.sh
      - name: checkout opentelemetry-cpp
        uses: actions/checkout@v2
        with: 
          repository: "open-telemetry/opentelemetry-cpp"
          fetch-depth: 1
          path: "opentelemetry-cpp"
          submodules: "recursive"
      - name: build opentelemetry-cpp
        run: |
          ./ci/otel-cpp.sh 
      - name: build nginx module
        run: |
          ./ci/build_module.sh
      - name: Upload module artifact
        uses: actions/upload-artifact@v2
        with:
          name: otel-nginx
          path: build/otel_ngx_module.so
